# Generated by Django 5.2 on 2025-04-08 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_wallet_address_alter_invoice_crypto_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(default='My API Key', help_text='A name to identify this API key', max_length=100),
        ),
        migrations.AddField(
            model_name='apikey',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='Test mode keys can only create test charges'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_type', models.CharField(max_length=10)),
                ('wallet_address', models.CharField(max_length=255)),
                ('wallet_source', models.CharField(choices=[('Manual', 'Manual'), ('Revolut', 'Revolut'), ('Bybit', 'Bybit')], default='Manual', max_length=10)),
                ('network', models.CharField(blank=True, choices=[('Bitcoin Network', 'Bitcoin Network'), ('Ethereum Network', 'Ethereum Network'), ('Solana Network', 'Solana Network'), ('BNB Chain', 'BNB Chain'), ('XRP Ledger', 'XRP Ledger'), ('Cardano Network', 'Cardano Network'), ('Dogecoin Network', 'Dogecoin Network'), ('Avalanche Network', 'Avalanche Network')], max_length=20)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'crypto_type', 'wallet_address')},
            },
        ),
    ]
