# Generated by Django 5.2 on 2025-04-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_apikey_options_apikey_last_used_at_apikey_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='crypto_type',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('BNB', 'Binance Coin'), ('XRP', 'XRP'), ('USDT', 'Tether'), ('USDC', 'USD Coin'), ('ADA', 'Cardano'), ('DOGE', 'Dogecoin'), ('AVAX', 'Avalanche')], max_length=10),
        ),
    ]
